### PR TITLE
Add lower cpu clocks to sys-clk-OC and add some info to readme 

### PR DESCRIPTION
**Pull request by Anxietytimmy**
Basically add lower clocks as some games can use go down to 408mhz (Like Sonic Mania). Also add some info in the readme about 921+ erista oc.

### CODE REVIEW

**Comment by KazushiMe** [comment]
Thanks for your PR.

1. Lowering CPU clocks below 1020 MHz does decrease power draw by limiting voltage on Erista ([cpu cvb table](https://github.com/KazushiMe/Switch-OC-Suite/blob/master/Source/Atmosphere/stratosphere/loader/source/oc/ldr_oc_suite.cpp#L951)), while on Mariko it does not. Mariko @ 1020 MHz requests its minimum voltage (610mV) already, so actually I'm thinking of removing anything lower than 1020 MHz.
  -  Undervolting (lowering min volt) is possible, but it requires intensive tests and does not work on all units.

2. Those Erista GPU tests > 921 MHz (along with Mariko GPU > 1.3 GHz) were conducted before HOS PLL limit was removed. Now higher clocks might literally work, but I don't see any game could fully utilize GPU above 921 MHz. And it's pointless to risk 50-100mV increase for that 2% margin of performance.

**Comment by Anxietytimmy** [comment]
I think smt V probably would be able to use 921+, but I tested and it exceeds the 18W limit on erista.

**Comment by Cooler3D** [comment]
> 2\. Those Erista GPU tests > 921 MHz (along with Mariko GPU > 1.3 GHz) were conducted before HOS PLL limit was removed. Now higher clocks might literally work, but I don't see any game could fully utilize GPU above 921 MHz. And it's pointless to risk 50-100mV increase for that 2% margin of performance.

A lot of games are capable of this if you use graphical modifications to them. For testing, I used the Witcher configuration, which maximizes graphics settings, fixes native resolution, and also removes the frame rate cap. At frequencies of 2397MHz / 1305MHz / 2131MHz, the game produces an average of 45 frames per second. I'll try to check for performance gains from removing the power cap soon.

**Comment by KazushiMe** [comment]
Added in 139c7df, which also brought Erista CPU OC up to 2091 MHz.

**Pull request closed without merging**
